// 新闻链接

let newsData = [
	{
		type:'Web开发技术',
		id:1,
		content:[
			{
				url:'https://youzan.github.io/vant/v2/#/zh-CN/notice-bar',
				title:'vantUI-一款移动端UI框架',
				date:'2022-03-09',
				id:101,
				important:false
			},
			{
				url:'https://element.eleme.cn/#/zh-CN',
				title:'Element-Ui 最受欢迎的UI框架',
				date:'2022-03-09',
				id:102,
				important:false
			},
			{
				url:'http://hnclove.com/',
				title:'适合新手的前端小案例',
				date:'2022-03-09',
				id:103,
				important:false
			},
			{
				url:'https://bazhan.wang/',
				title:'在线扒站工具-将别人网页扒成代码',
				date:'2022-03-09',
				id:104,
				important:true
			},
			{
				url:'https://juejin.cn/',
				title:'掘金-程序员摸鱼之家',
				date:'2022-03-09',
				id:105,
				important:false
			},
			{
				url:'http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html',
				title:'flex布局-阮一峰',
				date:'2022-03-09',
				id:106,
				important:true
			}
		]
	},
	{
		type:'UI技术分享',
		id:2,
		content:[
			{
				url:'https://www.ui.cn/detail/615375.html',
				title:'对软件排版的一些浅层认知',
				date:'2022-03-08',
				id:107,
				important:false
			},
			{
				url:'https://www.ui.cn/detail/615524.html',
				title:'B端表格设计指南',
				date:'2022-03-08',
				id:108,
				important:false
			},
			{
				url:'https://www.ui.cn/detail/615689.html',
				title:'设计中的留白：每个设计师都应该知道的留白准则',
				date:'2022-03-08',
				id:109,
				important:true
			},
			{
				url:'https://www.ui.cn/detail/616025.html',
				title:'2022 年 10 大移动应用 UI 设计理念',
				date:'2022-03-09',
				id:110,
				important:false
			},
			{
				url:'https://www.ui.cn/detail/616676.html',
				title:'一些被忽略的 UI 设计表现技巧',
				date:'2022-03-08',
				id:111,
				important:false
			},
			{
				url:'https://www.ui.cn/detail/617012.html',
				title:'图标篇 | 图标设计必备的基础知识！',
				date:'2022-03-08',
				id:112,
				important:true
			}
		]
	},
	{
		type:'行业新闻',
		id:3,
		content:[
			{
				url:'https://juejin.cn/post/6844903448660410376',
				title:'多年 JavaScript 学习笔记整理',
				date:'2016-10-28',
				id:113,
				important:false
			},
			{
				url:'https://juejin.cn/post/6847009772349177869',
				title:'自制力提升、学习方法分享',
				date:'2020-07-08',
				id:114,
				important:true
			},
			{
				url:'https://juejin.cn/post/6960566171351384072',
				title:'浅谈前端程序员的学习',
				date:'2021-05-10',
				id:115,
				important:false
			},
			{
				url:'https://juejin.cn/post/6844903445451784200',
				title:'思维导图来学习Javascript基础知识',
				date:'2016-09-28',
				id:116,
				important:false
			},
			{
				url:'https://www.jianshu.com/p/03f9fa94c474',
				title:'vue-awesome-swiper的正确使用姿势',
				date:'2021-04-16',
				id:117,
				important:false
			},
			{
				url:'https://www.jianshu.com/p/a9401aa5219c',
				title:'移动端vue项目模板',
				date:'2019-05-17',
				id:118,
				important:true
			}
		]
	}
]

let officeList = [
	{
		name:'岳麓区办公室',
		addres:'长沙市岳麓区奥克斯国际公馆B栋9043号',
		email:'467173059@qq.com',
		phone:'0731-85503113',
		url:'https:www.tianmakeji.cn',
		id:1,
		img:require('@/assets/img/office1.png')
	},
	{
		name:'天心区办公室',
		addres:'长沙市天心区芙蓉中路266号弘林国际大厦',
		email:'467173059@qq.com',
		phone:'0731-85503113',
		url:'https:www.tianmakeji.cn',
		id:2,
		img:require('@/assets/img/office2.jpg')
	}	
]

let serveList = [
	{
		img:require('@/assets/img/serve/1-1.jpg'),
		id:1,
		name:'数据中心联盟',
		fn:'网站改版'
	},
	{
		img:require('@/assets/img/serve/1-2.jpg'),
		id:2,
		name:'荒草地',
		fn:'品牌设计'
	},
	{
		img:require('@/assets/img/serve/1-3.jpg'),
		id:3,
		name:'京东金融',
		fn:'UI设计'
	},
	{
		img:require('@/assets/img/serve/1-4.jpg'),
		id:4,
		name:'中国婚博会',
		fn:'APP设计'
	},
	{
		img:require('@/assets/img/serve/2-1.jpg'),
		id:5,
		name:'中信银行',
		fn:'网站改版'
	},
	{
		img:require('@/assets/img/serve/2-2.jpg'),
		id:6,
		name:'国金基金',
		fn:'产品设计'
	},
	{
		img:require('@/assets/img/serve/2-3.jpg'),
		id:7,
		name:'合一金融',
		fn:'网站改版'
	},
	{
		img:require('@/assets/img/serve/2-4.jpg'),
		id:8,
		name:'中央音乐学院',
		fn:'广告创意设计'
	},
	{
		img:require('@/assets/img/serve/3-1.jpg'),
		id:9,
		name:'CBRE',
		fn:'VI设计'
	},
	{
		img:require('@/assets/img/serve/3-2.jpg'),
		id:10,
		name:'中国建设银行',
		fn:'业务系统设计'
	},
	{
		img:require('@/assets/img/serve/3-3.jpg'),
		id:11,
		name:'富通经纬',
		fn:'业务系统设计'
	},
	{
		img:require('@/assets/img/serve/3-4.jpg'),
		id:12,
		name:'豆丁网',
		fn:'UI设计'
	},
	{
		img:require('@/assets/img/serve/4-1.jpg'),
		id:13,
		name:'凤凰艺术网',
		fn:'APP设计'
	},
	{
		img:require('@/assets/img/serve/4-2.jpg'),
		id:14,
		name:'益乐尚',
		fn:'官网设计'
	},
	{
		img:require('@/assets/img/serve/4-3.jpg'),
		id:15,
		name:'博智云翼',
		fn:'企业官网设计'
	},
	{
		img:require('@/assets/img/serve/4-4.jpg'),
		id:16,
		name:'中信金融网',
		fn:'品牌设计'
	}
]
export{
	newsData,officeList,serveList
}